version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: make test
      - run: go test -race -coverprofile=profile.out -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
